FROM adoptopenjdk/openjdk11:s390x-ubi-minimal-jre-11.0.16.1_1
ARG JAR_FILE=target/*.jar
ARG OTEL_JAVA_AGENT_JAR_FILE=opentelemetry-javaagent.jar
COPY ${JAR_FILE} application.jar
COPY ${OTEL_JAVA_AGENT_JAR_FILE} opentelemetry-javaagent.jar
EXPOSE 8081
ENTRYPOINT ["java","-javaagent:/opentelemetry-javaagent.jar","-Dotel.service.name=api-service","-jar","/application.jar"]